name: Build Backend and Push Docker Image

on:
  push:
    branches:
      - main # change if you want to trigger on different branches
    paths:
      - "backend/**"

# Required so we can push to GHCR
permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set Docker tag
        # Creates an environment variable "DOCKER_TAG" in the form "YYYYMMDDHHMMSS-abcdefg"
        run: echo "DOCKER_TAG=$(date +'%Y%m%d%H%M%S')-$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

      - name: Determine branch suffix
        run: |
          # e.g. "main", "feature/my-branch", etc.
          BRANCH_NAME="${{ github.ref_name }}"

          if [ "$BRANCH_NAME" = "main" ]; then
            # If it's the default branch "main", no suffix
            echo "BRANCH_SUFFIX=" >> $GITHUB_ENV
          else
            # For other branches, we append '/branch-name'
            # Replace slashes with dashes to avoid invalid repo names
            SANITIZED_BRANCH=$(echo "$BRANCH_NAME" | tr '/' '-')
            echo "BRANCH_SUFFIX=/$SANITIZED_BRANCH" >> $GITHUB_ENV
          fi

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -f backend/Dockerfile -t ghcr.io/${{ github.repository }}/backend${{ env.BRANCH_SUFFIX }}:${{ env.DOCKER_TAG }} ./backend

          docker push ghcr.io/${{ github.repository }}/backend${{ env.BRANCH_SUFFIX }}:${{ env.DOCKER_TAG }}
